### ISSUE TITLE
Android: node_modules/react-native-image-crop-picker/example/android': could not setcwd() (errno 2: No such file or directory)

### ISSUE THREAD

**Issue by karltaylor** [ivpusic/react-native-image-crop-picker#1073]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.25.0
- react-native v0.60.4

`react-native info` dump

```bash
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 4.13 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

App to compile

### Actual behaviour

App does not compile

```bash
Could not set process working directory to '/node_modules/react-native-image-crop-picker/example/android': could not setcwd() (errno 2: No such file or directory)
```

### Steps to reproduce

Install `react-native-image-crop-picker` and open / build android project

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by dougantrhoupa** [comment]
Same error on react-native-image-crop-picker v0.25.0 and react-native v0.60.4 too

**Comment by joeljerushan** [comment]
i'm getting same error 👎 can anyone help

**Comment by jiangjiatao** [comment]
me too

**Comment by jiangjiatao** [comment]
@andrey-tsaplin  @ivpusic   me too !!!!

**Comment by karltaylor** [comment]
I got my Android app working by using [jetifier](https://github.com/mikehardy/jetifier#to-jetify--convert-node_modules-dependencies-to-androidx).

After running upgrading to React Native `0.60.4` opened Android Studio + open device manager to make sure you have an Android Emulator running.

When you run `npx react-native android` it will run Jetifier before it runs your RN App.

Unfortunately I can't get Android Studio to play nicely

**Comment by stefen** [comment]
In the meantime, just make the missing folder (no content necessary) to get your app building again.

I'm curious why this would only crop up now, when my environment doesn't appear to have changed, I haven't updated the library recently, and it appears to also be a recent occurrence for others.

**Comment by karltaylor** [comment]
Yep `mkdir -p node_modules/react-native-image-crop-picker/example/android/` removed this error for me

**Comment by xiong34664** [comment]
Still no one solved? Novices feel very difficult

**Comment by Phecda** [comment]
This seems to be caused by `android/react-native-image-crop-picker.iml` in the npm package. The temporary solution is to remove it manually or with some tools like `patch-package`. @ivpusic I think this file should be exclueded on next release. (Maybe `.npmignore` or `.gitignore`?)
(Actually I think those other than `src` and `build.gradle` should also be ignored. 🤔)

**Comment by WdBly** [comment]
I have the same problem,  react-native v0.61.2 and react-native-image-crop-picker v0.26.0

**Comment by ivpusic** [comment]
fix released in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.26.1

**Comment by bneigher** [comment]
@ivpusic this is still an issue for me.. is anyone else still seeing this with ^0.32.0 or am I nuts
