### ISSUE TITLE
Gif files are returned as jpeg

### ISSUE THREAD

**Issue by fega** [ivpusic/react-native-image-crop-picker#1113]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.25.2
- react-native v0.59.8

### Platform
IOS
### Expected behaviour
I'd expect as mentioned in previous comments that if I set compressImageQuality as undefined it will return original image but it doesn't work (I tried also with values like 1, 100 and null, but i'm getting the same)

### Actual behaviour

image is a JPEG

### Steps to reproduce
```
const options= {}
ImagePicker.openPicker(options).then(response => {
        console.log('MIME TYPE= ', response.mime)
});
```
### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by brandonpearcy** [comment]
I can also confirm this is happening. If a user selects an animated GIF, the result is a static JPEG instead.

**Comment by Adarwall** [comment]
Did you find a solution? I'm facing the same issue...

**Comment by brunowbbs** [comment]
Did you find a solution?

**Comment by STIENLILLY** [comment]
Same issue on RN 0.62.2

**Comment by STIENLILLY** [comment]
https://github.com/ivpusic/react-native-image-crop-picker/blob/da9af08384c35dcd3be154cdb6d5c579b48b338a/ios/src/ImageCropPicker.m#L828-L841

'filePath' is forced to jpg extension that is created by the 'writeTempFile' option.

**Comment by STIENLILLY** [comment]
https://github.com/ivpusic/react-native-image-crop-picker/pull/1301 Check for my PR.

**Comment by omarinho** [comment]
Apparently the same is happening with .BPM extension,

**Comment by STIENLILLY** [comment]
@omarinho .bpm is not support to extension but you can customize persistFile function to support bpm

**Comment by PointCodeZero** [comment]
I saw that a fix was merged here [#1301 ](https://github.com/ivpusic/react-native-image-crop-picker/pull/1301). Any plans on publishing this fix on v.0.25.3 for RN 0.60? It would be a saviour for us!

**Comment by LeonelRiera** [comment]
Any news with this fix? It seems correct but why has it not been merged after years? .gif is still not working and it is still returning a .jpg
