### ISSUE TITLE
iOS 14 - Error: Cannot process video data

### ISSUE THREAD

**Issue by Abhishek-Sankey** [ivpusic/react-native-image-crop-picker#1479]
### Version

- react-native-image-crop-picker v0.35.0
- react-native v0.63.3

### Platform

- iOS(14)

**Issue:**
Try to select a video from the photos, the video doesn't upload.
ImagePicker.openPicker({
		compressVideoPreset:'HighQuality',
	}).then(video => {})
Promise throws an exception.

**Exception**
{ 
code: E_CANNOT_PROCESS_VIDEO,
message: Cannot process video data,
domain: RCTErrorDomain,
userInfo: null,
}
Can someone plz help???
Thanks in advance!

**Comment by snamstorm** [comment]
Have also seen this happen on some videos 

Tried to upload a .mov file and got this error on iOS 14. Tried the same file on iOS 13 and no issue

**Comment by ShotSkydiver** [comment]
this is a _huge_ issue for our app and how we use this library, I see this issue with every video I've tried on multiple iOS 14 devices

**Comment by ShotSkydiver** [comment]
just FYI, for me at least, setting the compressVideoPreset to anything other than "MediumQuality" seems to fix this issue for me entirely, setting it to "HighestQuality" or "Passthrough" works perfectly fine for me on videos that previously had issues processing

**Comment by Abhishek-Sankey** [comment]
@ShotSkydiver getting this issue on compressVideoPreset set as `HighQuality` only. Not working for me.

**Comment by ShotSkydiver** [comment]
> @ShotSkydiver getting this issue on compressVideoPreset set as `HighQuality` only. Not working for me.

if you're setting it to "HighQuality" specifically, that's not a valid string, the actual string is "HighestQuality"

**Comment by vladpanov** [comment]
Same issue. In my case, getting this error for images/videos store in iCloud.

To replicate this issue, make sure you have the "Optimize iPhone Storage" feature enabled (default on iOS14, I believe) and select an older image/video.

Btw, there is a related discussion on this (if I am not mistaken) here:
https://github.com/ivpusic/react-native-image-crop-picker/issues/1415

**Comment by dcheema6** [comment]
@ShotSkydiver thax, this fixed the issue for me...

**Comment by huzaifaaak** [comment]
@ivpusic is this issue fixed in any latest release ? Otherwise I can create a PR with code in #1415 ?

**Comment by RadosavAntonio** [comment]
Is still happening for me on lib version 0.42.0 with RN 0.75.3 and iOS min deployment version 15.1

```
    const video = await ImagePicker.openPicker({
      mediaType: 'video',
      compressVideoPreset: 'MediumQuality',
      videoQuality: 'medium',
      maxFiles: 1,
    })
```
