### ISSUE TITLE
The image after compress has a white bottom border line, and the height is not a int.

### ISSUE THREAD

**Issue by jaggerwang** [ivpusic/react-native-image-crop-picker#186]
### Version

- react-native-image-crop-picker v0.11.0
- react-native v0.39.2

### Platform

- iOS

### Expected

No border line, and height should be a int.

### Actual

As the title.

### Steps to reproduce

The compression options are as follow.

```javascript
{
        compressImageMaxWidth: 1080,
        compressImageMaxHeight: 810,
        compressImageQuality: 0.9,
}
```

### Attachments

![image](https://cloud.githubusercontent.com/assets/1255011/21687457/53ae352c-d3a4-11e6-87c0-4c26e0840d02.png)

![image](https://cloud.githubusercontent.com/assets/1255011/21687601/e0d23804-d3a4-11e6-943b-f71dd2b378a0.png)

**Comment by ivpusic** [comment]
fixed in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.12.1

**Comment by jyling** [comment]
Incase someone is getting the white line issue https://github.com/ivpusic/react-native-image-crop-picker/issues/984, make sure your width and height match your image's width and height

**Comment by Etaliya** [comment]
@ivpusic  If we keep playing with a crop then the white border still showing in the bottom.

**Comment by Robiullah2244** [comment]
Any solution? I am facing the same issue.
