### ISSUE TITLE
How remove crop quality ?

### ISSUE THREAD

**Issue by userbq201** [ivpusic/react-native-image-crop-picker#719]
1) Get photo
2) Crop photo

result - very bad quality. Wtf ?

**Comment by ivpusic** [comment]
fixed here https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.21.2

**Comment by msqar** [comment]
@ivpusic it seems it didn't fix it, i'm using 0.25.2 and still happens. Any ideas?
