### ISSUE TITLE
Issue with uploading on Android.

### ISSUE THREAD

**Issue by 3luyka** [ivpusic/react-native-image-crop-picker#807]
Hey all, I've issue with uploading images to the server on Android. Here's example of my code:

```
const photo = await ImagePicker.openPicker({
  mediaType: 'photo',
  cropping: true,
  forceJpg: true
});

const data = new FormData();
data.append('uploadFile', {
  uri: photo.path, // file:///data ....
  name: photo.filename,
  type: photo.mime
});
```

On iOS everything is ok.  

### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.1
- react-native v0.56.0

### Platform
- Android

**Comment by boyrt** [comment]
DocumentsContract

**Comment by boyrt** [comment]
I am also getting issue .

**Comment by Anujmoglix** [comment]
Any solution ?

**Comment by 3luyka** [comment]
@ivpusic any suggestions?

**Comment by 3luyka** [comment]
Issue is solved. I missed that's "filename" doesn't exists on Android platform (iOS only). So I just replaced `name: photo.filename` with 
```
const parts = photo.path.split('/');

name: parts[parts.length - 1]
```

**Comment by Anujmoglix** [comment]
but i am still getting error here and not able to upload file

**Comment by anagar23** [comment]
@Anujmoglix, Yes, I am also getting error for Android. It works fine for iOS. Are you able to sovle the problem?

@3luyka , Are you sending file path to the server ?

**Comment by Infokora** [comment]
someone has solved this issue?

**Comment by aniksharif** [comment]
@Infokora I followed the @3luyka 's way. That works!

**Comment by aniksharif** [comment]
@Infokora this is my code(it works!)
 const parts = image.path.split('/')
                                let uri =image.path
                                let name= parts[parts.length - 1]
                                let type= image.mime
                             const file={
                                    uri,
                                    name,
                                    type,
                                
                                }
                                const body= new FormData()
                             
                                body.append('photo',file)
                                
                                let response_photo = await fetch(url_img, {
                                    method: 'PUT',
                                
                                body
                                    
                                
                                });
