### ISSUE TITLE
When taking a photo from the camera, causing the app to restart

### ISSUE THREAD

**Issue by ShuChangSC** [ivpusic/react-native-image-crop-picker#955]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.23.0
- react-native v0.55.4

### Platform
- Android

### Expected behaviour
Take a picture from the camera and display it

### Actual behaviour
When taking a photo from the camera, causing the app to restart

### Steps to reproduce
takeByCamera = () => {
    ImagePicker.openCamera({
      width: 400,
      height: 400,
    })
      .then(image => {
        console.log(image);
        this.setState({
          avatarPath: {uri: image.path}
        })
      })
      .catch(error => {
        console.log(error)
      })
  };

### Attachments

rRestart the app frequently,but sometimes it is ok

**Comment by divyamantri1292** [comment]
I am facing same issue.

**Comment by krewllobster** [comment]
I am also facing the same issue. Moto X4, android v9

Also restarts app like 90% of the time, but sometimes its ok. I've tried decreasing compressed size and quality to try and help if its a memory thing, but that did nothing.

**Comment by filipef101** [comment]
Same thing seems like the camera view is closing the app. Can you guys see if not taking a picture and going back, our app is closed or restarting?

**Comment by filipef101** [comment]
probably duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/836

**Comment by krewllobster** [comment]
@filipef101 yes, it also sometimes crashes when attempting to use the android back-button to go back to the main app. This seems like a wide-spread issue over many versions of the library and over many versions of Android operating systems. The earliest issue I could find was #240 (crash after photo confirm on android) from Feb 2017. This thread now is the most recent. Other issue threads, all of which are still open are: 

1. #240 
2. #378 
3. #501 (maybe related)
4. #505 
5. #519 
6. #648 (maybe related)
7. #822 (maybe related)
8. #836 
9. #900

**Comment by filipef101** [comment]
Basically the issue is that the Camera Screen is an independent screen that then passes the data to JS, this is my assumsion.
This probably can be solved by using other lib to take the photo then use this on to crop it.
If I face this issue on my app I'll share the solution here.
As so far I only noticed this on debug

**Comment by krewllobster** [comment]
Here's the memory profile as the camera opens: 

<img width="1079" alt="Screen Shot 2019-03-28 at 12 18 15 PM" src="https://user-images.githubusercontent.com/9201597/55174428-caea5100-5153-11e9-9f6a-5aebb5010537.png">

It just tanks down to zero, and I don't think that it was over-using before? Here's the full session profile, I'm not experienced enough to know if it looks ok or not:

<img width="1079" alt="Screen Shot 2019-03-28 at 12 17 33 PM" src="https://user-images.githubusercontent.com/9201597/55174471-e0f81180-5153-11e9-83eb-46d84eb711c6.png">

**Comment by krewllobster** [comment]
@filipef101 Also, I came to this library after I started getting this problem with react-native-image-picker.

The only other library I can find is react-native-camera, which I guess creates a camera view as a react component, rather than opening the camera intent over the app? If it does work like that, do you think it would solve this issue?

**Comment by filipef101** [comment]
Yup, probably does,
I never used that one but used but did use react-native-camera-kit to implement my custom camera view (like a year ago, had a few issues with it and needed to fork it)

But react-native-camera certainly doesn't have this issue so you can pass the image it gives you and use this library to crop it.
It's a matter of making that seamless

**Comment by filipef101** [comment]
Also so far I don't face this on my release, might be only happening if you use too much memory

**Comment by krewllobster** [comment]
Yeah, I'm spending today cleaning up my code-base. Uninstalling unused dependencies, making sure I'm only requiring what I need from libs, etc. We'll see if that helps at all. If it doesn't I'm going to be super disappointed, but it needs to be done regardless.

**Comment by krewllobster** [comment]
@ivpusic @filipef101 The strange thing is that the camera activity takes enough memory to force the OS to kill the RN Activity. The RN Activity is saved -> stopped -> destroyed, and when the camera activity tries to pass information back to the RN Activity, rather than starting from a saved state, its starting from a fresh state.

Is this potentially something in my mainActivity.java file where I don't have the appropriate onStop() and onStart() handlers that should be saving the app state? Again, not an Android dev here, but something fishy is going on.

In issue #519, @pisacode mentioned that he was using react-native-splash-screen. The recommended setup for RNSplashScreen is to have a SplashActivity.java file that looks like this:

```
public class SplashActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle SavedInstanceState) {
        super.onCreate(SavedInstanceState);

        Intent intent = new Intent(this, MainActivity.class);

        startActivity(intent);
        finish();
    }
}
```

So then my MainActivity.java looks like this:

```
public class MainActivity extends ReactActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        SplashScreen.show(this);
        super.onCreate(savedInstanceState);
    }
    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "***myPackageName***";
    }
}
```

Is it not receiving a savedInstanceState properly? I have no onStop() or onPause() methods on my MainApplication.java class.

**Comment by osdamv** [comment]
It happens in some devices when you open the camera, the camera request more RAM therefore closing all the the apps(it do not crash the app), in order to reproduce the problem there is the need to enable in the developer tools the option called "Don't keep activities".

The fix in my case was very simple, just the persist the state of my app using redux-persist.

**Comment by ostar0816** [comment]
I also suffered all the day and found it doesn't happen in the release apk.
I am using react-native v0.59.1 and react-native-image-crop-picker v0.23.1. Please build the apk with `gradlew assembleRelease` in terminal, not exporting wizard in Android Studio.
Hope it helps.

**Comment by fernandofranca** [comment]
I'm having the same issue.
The issue doesn't happen when there are no other apps consuming memory.

# Version
```
"react-native-image-crop-picker": "^0.24.1"
"react-native": "0.58.5"
```

# Platform
Android

**Comment by barbsicle** [comment]
Hi. I did a lot of digging after coming across this issue across some phones with extremely aggressive backgrounding (see [here](https://dontkillmyapp.com/) for a list). 

After various attempts at all kinds of solutions (e.g. foreground service, `react-native-background-timer`, etc.), I found that the best solution was offered by @osdamv where we persist navigation state (and possibly redux state) and rehydrate the app when it returns from the camera. I recommend testing with "Don't keep activities" via the Android developer tools.

Unfortunately, for a potential fix for the library itself, I can't confidently say it can be done. Most of the research I've done on Android usually reverts back to saving instance state anyway.

**Comment by Strate** [comment]
I think one of possible solution could be not use such kind of libraries (like react-native-image-crop-picker, react-native-image-picker), but implement camera/library picking interface using react-native-camera & CameraRoll

**Comment by rmamtaventures** [comment]
App restart on mi device when taking pic from camera.

**Comment by ShuChangSC** [comment]
Yes,right,i develop on Redmi device.




| |
idealchang
邮箱：idealchang@163.com
|

Signature is customized by Netease Mail Master

On 10/22/2019 20:11, rmamtaventures wrote:

App restart on mi device when taking pic from camera.

**Comment by rmamtaventures** [comment]
Any solution of app restart?

**Comment by bbored** [comment]
Hi, I found a workaround that reduce the number of app' crashes.

add dexoptions in app build.gradle:

android { dexOptions { javaMaxHeapSize "8g" } }


add  JVM heap size in gradle.properties:

org.gradle.jvmargs=-Xmx9216M


Please let me know if this help, I'm still testing.

**Comment by rmamtaventures** [comment]
These settings are already done but not working.

**Comment by rmamtaventures** [comment]
Any update on app restart issue?

**Comment by viv3kk** [comment]
Any update on app restart issue?

**Comment by engineerahkhani** [comment]
Any update on app restart issue?

**Comment by Hamawis** [comment]
any update?

**Comment by FranklinSilva** [comment]
Guys, 
I managed to solve by defining a smaller size in the target picture and enable the crop. In fact, the images were too large when it comes to sizes (over 3000x3000 px). Here is how I'm calling the camera on Android devices.

`  ImagePicker.openCamera({
            width: 500,
            height: 400,
            cropping: true,
            compressImageQuality: 0.4,
          }).then(image => {
            //do some processing
            }
          });`

**Comment by 12343954** [comment]
doesn't work on reduce image size ! still restart the app after click "OK"
Realme X on Android 10

**Comment by kluas11** [comment]
The restart problem also appeared in Huawei P20 Pro

**Comment by victorwpbastos** [comment]
I fixed this by asking the permissions on Android and iOS (using react-native-permissions lib):

```
useEffect(() => {
    async function askPermissions() {
        if (Platform.OS === 'android') {
            await Permissions.requestMultiple([
                'android.permission.CAMERA',
                'android.permission.WRITE_EXTERNAL_STORAGE',
            ]);
        }

        if (Platform.OS === 'ios') {
            await Permissions.requestMultiple(['ios.permission.CAMERA', 'ios.permission.PHOTO_LIBRARY']);
        }
    }

    askPermissions();
}, []);
```

**Comment by douglasjunior** [comment]
The problem is not the permissions, because the restart happens after opening the camera, that is, the permission has already been granted.

**Comment by victorwpbastos** [comment]
I started to ask the permissions before the user press the button to open the camera. In my case this works.

**Comment by douglasjunior** [comment]
According to the reports of this project and also of the `react-native-image-picker` https://github.com/react-native-community/react-native-image-picker/issues/732, the problem is related to the image size and memory consumption.

In many cases the restart happens even after the permissions have been granted for a long time.

Probably in your case the permissions were coincidental.

**Comment by nobady90** [comment]
I followed the instructions of @FranklinSilva  and @douglasjunior , added this in the options:

```
quality: 0.9,
maxWidth: 1200,
maxHeight: 1200,
```

now it no longer gave me the problem of restarting the app after shooting on the device I was testing with, that is a huawei with emui 9.1.0 and android 9. Thanks

**Comment by tegozen** [comment]
the company suggests that you need to save the state at the time of onStop, and restore it on onCreate. in MainActivity, but I don't have the code. for those who do not know what to do, there is a solution without using this library. You can output a stream from the camera directly to the react-native app using react-native-camera. And to get photos from the library and crop them, use this library.

**Comment by ZeeshanAhmadKhalil** [comment]
I am facing this issue because of memory as well. When I open **ImagePicker** it actually shows the recent images. From there I go to the gallery and from the gallery, I can select Camera Folder and here I pick the image. I think these are a lot of activities which fills up the memory and due to this my app restarts.

**Comment by Seamus1989** [comment]
+1

**Comment by Anzormumladze** [comment]
+1

**Comment by HugoGresse** [comment]
Upon investigation, I was able to reproduce the exact issue on a Redmi 7A with MIUI Global 12.0.1 stable (should also be possible on the readmi 8) 

From [this comment](https://github.com/ivpusic/react-native-image-crop-picker/issues/955#issuecomment-477656569) in this thread, this is related to a lot of issues. 

Upon more investigation, I believe this also happen on other modules: 
- https://github.com/expo/expo/issues/11103
- https://github.com/react-native-image-picker/react-native-image-picker/issues/1502

The reason is related to the Activity being killed by those android version (really related to the constructor version, no bug in MIUI 11, bug in MIUI 12) and more important `ReactContext` being null on activty restart with results : 

MainActivity
```
  @Override
  public void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);

    Log.d("onActivityResult", "null context? " + (getReactInstanceManager().getCurrentReactContext() == null));
  }
  ```
  The above return `false` on most phones, and `true` on some devices. 
  
  
  For the sake of cross-referencing most related issues from other modules and working on a workaround, I've created a repo: https://github.com/HugoGresse/react-native-issue-30277/blob/main/README.md

**Comment by HugoGresse** [comment]
Ok, after some time I was able to find a workaround, see [here](https://github.com/HugoGresse/react-native-issue-30277/blob/main/PATCH-react-native-image-crop-picker.md). 
You should be able to use it on your projects without too much pain.

**Comment by howg0924** [comment]
@HugoGresse Thank you so much for trying to solve this long existing problem~~. ❤ Is it also possible to modify your solution to fix similar problem in openPicker()?

Our users use openPicker() much more frequently than openCamera(). Some of them cannot upload their photos due to this Android may destroy parent activity and app restart problem. 

Possible related issues: #1509 #1519 #505 #1490 #1195 #1517 #435 #1435 #471 #447 #318

**Comment by HugoGresse** [comment]
yes surely, that's why the repo is public and in MIT. Feel free to open a pull request. I was not able to reproduce this issue with the file picker on my side on the Redmi 7A MIUI 12 though.

**Comment by howg0924** [comment]
@HugoGresse I turned on "Don't keep activities" on my OPPO A73 and Genymotion emulator, both restarted the app after I selected an image in openPicker():

1.OPPO A73(CPH1725), ColorOS 3.2, Android 7.1.1
2.Genymotion Google Pixel, Android 8.0 (API 26)

**Comment by HugoGresse** [comment]
> @HugoGresse I turned on "Don't keep activities" on my OPPO A73 and Genymotion emulator, both restarted the app after I selected an image in openPicker():
> 
> 1.OPPO A73(CPH1725), ColorOS 3.2, Android 7.1.1
> 2.Genymotion Google Pixel, Android 8.0 (API 26)

Yes, they restart the app but on the Redmi 7A at least, the promise from ImagePicker was actualy resolved before the app is restarted, meaning it's resolved in a dead Activity (checked using a plain console.log). (with Don't keep activities). 
Could you confirm this is not the case on your side?

**Comment by howg0924** [comment]
@HugoGresse I just tested it. The promise from ImagePicker does not resolve before the app is restarted. I'm using RN 0.59.10, react-native-image-crop-picker 0.35.1, and react-native-navigation v1. Not sure whether this difference is caused by react-native-navigation.

Do you have any idea why openCamera() and openPicker() behave differently on your side since they both started another activity?

**Comment by HugoGresse** [comment]
I believe the file picker is way more memory hungry that the camera which may result in the app not being killed by android. I've completed the workaround on my production app and are waiting for beta testers to give some feedback. 

As a side note, there is some specifities for my workaround: first, it need some/a lot of adjustment to make it works (screen redirect, state adjustment on app open, etc). Plus we also need to take care of adding another photo on top of the current one, which I will prevent in my app but you may need to save the state in AsyncStorage to recover it more easily. 

Regarding the openPicker(), I don't think it should be very hard at all to adapt the workaround, though I can't as I'm not reproducing the issue yet.

**Comment by Azaz0723** [comment]
App restarts in one plus on taking picture from camera not always but many times facing this issue and working fine in other mobiles

**Comment by Strate** [comment]
I found that actually only application root component unmounting in this case (you can force this behavior of android in "Developer Options" -> "Apps" -> "Don't keep activities"), but JS context is still alive, so you can store state of your application outside of component (for example - global variable accessible everywhere), and check that state on your component mount, to deal with issue.

**Comment by Rc85** [comment]
This is what I am getting in my logs
```
03:13:42.173
18451
ReactNativeJNI
Memory warning (pressure level: TRIM_MEMORY_RUNNING_LOW) received by JS VM, ignoring because it's non-severe
03:13:42.366
18451
ReactNativeJNI
Memory warning (pressure level: TRIM_MEMORY_RUNNING_CRITICAL) received by JS VM, running a GC
03:13:42.649
18451
ReactNativeJNI
Memory warning (pressure level: TRIM_MEMORY_BACKGROUND) received by JS VM, running a GC
03:13:44.418
18451
ReactNativeJNI
Memory warning (pressure level: TRIM_MEMORY_MODERATE) received by JS VM, running a GC
03:13:44.642
18451
ReactNativeJNI
Memory warning (pressure level: TRIM_MEMORY_COMPLETE) received by JS VM, running a GC
IDDEN) received by JS VM, ignoring because it's non-severe
03:13:56.944
18451
ReactNativeJNI
Memory warning (pressure level: TRIM_MEMORY_MODERATE) received by JS VM, running a GC
03:14:00.642
1480
Start proc 29037:com.munchies.run.courier.android/u0a474 for content provider {com.munchies.run.courier.android/com.reactnative.ivpusic.imagepicker.IvpusicImagePickerFileProvider}
```

**Comment by spaceod** [comment]
Getting the same issue in HUAWEI POT-LX1 (Android 10) Device.

**Comment by IntuzRajZ** [comment]
I've the same issue on the Samsung S8 device where the app is restarted after picking the photo by Camera or Gallery, and the problem is that by mistake, the **"Don't keep activities"(Destroy every activity as soon as the user leaves it)** is on that device, so i've just disabled it at Settings -> Developer options -> Apps -> **"Don't keep activities"(Destroy every activity as soon as the user leaves it)**.

![Image](https://github.com/user-attachments/assets/c8d19ca6-aec2-4650-b27c-8eabb9c0821b)

**Comment by douglasjunior** [comment]
> I've the same issue on the Samsung S8 device where the app is restarted after picking the photo by Camera or Gallery, and the problem is that by mistake, the **"Don't keep activities"(Destroy every activity as soon as the user leaves it)** is on that device, so i've just disabled it at Settings -> Developer options -> Apps -> **"Don't keep activities"(Destroy every activity as soon as the user leaves it)**.
> 
> ![Image](https://github.com/user-attachments/assets/c8d19ca6-aec2-4650-b27c-8eabb9c0821b)

I don't think that is the case for most users, because normal users don't use developer mode.
