### ISSUE TITLE
Illegal callback invocation from native module.

### ISSUE THREAD

**Issue by hmolotsi** [ivpusic/react-native-image-crop-picker#977]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.23.1
- react-native v0.58.6

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
No crash.

### Actual behaviour
Illegal callback invocation from native module. This callback type only permists a single invocation from native code.

### Steps to reproduce

1. Call openPicker()

2. In the photo gallery, select a photo

3. Cancel (which takes you back to the photo gallery)

4. Cancel again (to go back to the calling app)

5. Instead it crashes.

### Attachments

  function chooseFromLibrary(fireBaseLocation, maxDimensions, callback) {
    ImagePicker.openPicker({
      mediaType: "photo",
      width: maxDimensions ? maxDimensions.x : 300,
      height: maxDimensions ? maxDimensions.y : 300,
      cropping: true,
    })
    .then((image) => ImageStorage.ProcessPhoto(fireBaseLocation, callback, image))
    .catch((e) => {
      console.log(e);
      return callback(null);
    });
  }

  function processPhoto(fireBaseLocation, callback, image) {
    if ( image && image.path ) {
      const firebaseManager = FirebaseManager.getInstance();
      const source = {uri: image.path.replace('file://', ''), isStatic: true};

      firebaseManager.storeImage(fireBaseLocation, source.uri, (fileURL) => {
        if ( callback ) {
          if ( fileURL ) {
            callback({uri: fileURL, isStatic: true});
          } else {
            callback(null);
          }
        }
      })
    } else {
      if ( callback ) {
        callback (null);
      }
    }
  }

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by yoyo0427** [comment]
the same issue

**Comment by SunChJ** [comment]
> the same issue

+1, wanna new version

**Comment by 3luyka** [comment]
same

**Comment by baiyuhong** [comment]
same

**Comment by cinnabarhorse** [comment]
I can confirm that this issue is still happening in RN 0.59.5 with 0.23.1. 

Code:

  ImagePicker.openPicker({
            width: 300,
            height: 400,
            cropping: true
        }).then(image => {
            console.log(image);
        }).catch((error) => {
            alert(error)
        });

It ignores my catch and causes the red warning screen to appear, with the error: Illegal callback from native module. This callback type only permits a single invocation from native code.

**Comment by cinnabarhorse** [comment]
Seems like the problem could be occurring because the original Promise is already called when the user cancels the image selection, so there should be another Promise to deal with cancelling the entire viewcontroller. 

https://medium.com/nycdev/calling-a-callback-multiple-times-in-a-react-native-module-5c3c61f2fca4

Can someone implement this?

**Comment by cinnabarhorse** [comment]
Possibly solved:

ImageCropPicker.m

// Crop image has been canceled.
- (void)imageCropViewControllerDidCancelCrop:
(RSKImageCropViewController *)controller {
    [self dismissCropper:controller selectionDone:NO completion:[self waitAnimationEnd:^{
        if (self.currentSelectionMode == CROPPING || [[self.options objectForKey:@"cropping"] boolValue]) {
            //self.reject(ERROR_PICKER_CANCEL_KEY, ERROR_PICKER_CANCEL_MSG, nil);
        }
    }]];
}

I commented out the self.reject which will prevent the Promise from expiring too early. Is there a better way to solve this error?

**Comment by howieyoung** [comment]
@joyshion's commit fixed this issue well

**Comment by damikdk** [comment]
Any update here? Can I resolve this issue without forking?

**Comment by ensep** [comment]
@cinnabarhorse very very thank you. i encountered this problem for three weeks.  problem is solved. thank you for efforts.

**Comment by simonmitchell** [comment]
For anyone coming here for a fix, one was released in `0.24.1` of this library!

**Comment by legshampoo** [comment]
amazing!  thanks @simonmitchell 

error is gone now, but it still throws a warning - 'unhandled promise rejection'

do you know how to get rid of that?

**Comment by nihp** [comment]
I am also facing the same issue when I launch image from Library and again try to crop the image. Here I need to click the choose twice and it shows the error as  **"Illegal callback invocation from the native module. This callback type only permits a single invocation from native code"**


I am using "react-native-image-crop-picker": "^0.22.0".

**Comment by nihp** [comment]
I have upgraded to the latest. Still facing the same issue
